### ISSUE TITLE
Arbitrary file upload vulnerability

### ISSUE THREAD

**Issue by lcashdol** [abcprintf/upload-image-with-ajax#1]
Hi,  
The code below changes the $ready flag to true if the file conforms to the size of < 1000000.  Reversing the check that the file is an image.  So, a .php file can be uploaded with only a warning allowing code execution.

$ready = false;
        if((($imageType == "image/jpeg") || ($imageType == "image/jpg") || ($imageType == "image/png"))&&in_array($fileExt, $validext)){
            $ready = true;
        }else{
            echo "was not an image<br>";
           /*You should abort the upload right here*/
        }
        if($_FILES["fileUpload"]["size"] < 1000000){
            $ready = true;
            echo "file size is ".$_FILES['fileUpload']["size"]."<br>";
        }else{
            echo "file was TOO BIG!";
        }

**Comment by abcprintf** [comment]
@lcashdol  Thank you for reporting, I made a correction.

(https://github.com/abcprintf/upload-image-with-ajax/commit/71436ba5102010397519d4b25ea57591cfb4974c)
